paths:
  /api/products:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: All Products
        "500":
          description: Server Error
        "400":
          description: Some Data is Missing

  /api/products/{id}:
    get:
      summary: Get one product
      parameters:
        - name: id
          in: path
          description: Product Identifier
      tags:
        - Products
      schema:
        $type: String
      responses:
        "200":
          description: one Product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Server Error
        "400":
          description: Some Data is Missing

components:
  schemas:
    Product:
      type: object
      required:
        - title
        - price
        - code
      properties:
        id:
          type: string
        title:
          type: string
        Owner:
          type: string
        description:
          type: string
        price:
          type: number
        thumbnail:
          type: string
        code:
          type: number
        stock:
          type: number
          default: 10
      example:
        id: "8294y318921AdD32"
        title: Fideos Moñito
        Owner: admin
        description: Fideo integral tipo moñito 500g
        price: 444
        thumbnail: "https://www.mayoristanet.com/media/catalog/product/cache/7c7e7e8fca0426f106cb3e3371a80f9c/A/0/A08137_5.JPG"
        code: 9232712
        stock: 10
